apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster addons — cert-manager, external-dns, image-updater

  sourceRepos:
    - https://github.com/Hoaqim/link-archiver-gitops
    - https://charts.jetstack.io
    - https://kubernetes-sigs.github.io/external-dns/
    - https://argoproj.github.io/argo-helm
    - https://aws.github.io/eks-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'   

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'