apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-archiver-api
  template:
    metadata:
      labels:
        app: link-archiver-api
    spec:
      serviceAccountName: link-archiver-api
      containers:
        - name: api
          image: 137583030918.dkr.ecr.eu-central-1.amazonaws.com/myapp/api
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: link-archiver-env
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            periodSeconds: 5
          resources:
            requests: { cpu: 50m,  memory: 64Mi }
            limits:   { cpu: 200m, memory: 128Mi }