apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"   
spec:
  project: infra
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.16.1
    helm:
      values: |
        installCRDs: true
        serviceAccount:
          create: true
          name: cert-manager
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::137583030918:role/cert-manager-irsa
        securityContext:
          fsGroup: 1001   # required for IRSA token volume on EKS
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true   