apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: link-archiver-prod

resources:
  - ../../base

images:
  - name: 137583030918.dkr.ecr.eu-central-1.amazonaws.com/myapp/api
    newTag: 0.1.0
  - name: 137583030918.dkr.ecr.eu-central-1.amazonaws.com/myapp/worker
    newTag: 0.1.0

configMapGenerator:
  - name: link-archiver-env
    literals:
      - HTTP_SERVER_ADDR=:8080
      - AWS_REGION=eu-central-1
      - SQS_QUEUE_URL=https://sqs.eu-central-1.amazonaws.com/137583030918/link-archiver-prod
      - S3_BUCKET=link-archiver-prod

patches:
  - target:
      kind: ServiceAccount
      name: link-archiver-api
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/link-archiver-api-prod
  - target:
      kind: ServiceAccount
      name: link-archiver-worker
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/link-archiver-worker-prod
  - target:
      kind: Ingress
      name: api
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.link-archiver.dev