apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: link-archiver
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: link-archiver-dev
          - env: prod
            namespace: link-archiver-prod
  template:
    metadata:
      name: link-archiver-{{.env}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          api=137583030918.dkr.ecr.eu-central-1.amazonaws.com/link-archiver/api,worker=137583030918.dkr.ecr.eu-central-1.amazonaws.com/link-archiver/worker
        argocd-image-updater.argoproj.io/api.update-strategy: semver
        argocd-image-updater.argoproj.io/worker.update-strategy: semver
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
    spec:
      project: link-archiver
      source:
        repoURL: https://github.com/Hoaqim/link-archiver-gitops
        targetRevision: main
        path: apps/link-archiver/overlays/{{.env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true